pipeline {
  agent any
  stages {
    stage('Hello') {
      steps {
        // Print "Hello World"
        echo 'Hello World'
        echo 'This is added'
      }
    }
    stage('Build') {
      steps {
        mkdir 'build'
        cd build
        cmake ..
        make
      }
    }
  }
}

