
pipeline {
  agent any
  stages {
    stage('Hello') {
      steps {
        // Print "Hello World"
        echo 'Hello World in PR'
      }
    }
    stage('build') {
      steps {
        cmake 
            buildDir: './build', 
            sourceDir: '.'
//         cmakeBuild buildDir: 'build', cleanBuild: true
      }
    }
  }
}
